"""
Report Builder – Build PR description theo template chuẩn
"""
from datetime import datetime
from typing import Any


class ReportBuilder:
    """Xây dựng PR body markdown đầy đủ."""

    def build(
        self,
        ticket_data: dict[str, Any],
        fix_report: dict[str, Any],
        test_results: dict[str, Any],
    ) -> str:
        """
        Tạo PR description đầy đủ từ tất cả dữ liệu pipeline.

        Args:
            ticket_data: Ticket info từ STEP A
            fix_report: Fix analysis từ STEP C
            test_results: Test results từ STEP B

        Returns:
            str: Markdown PR body
        """
        ticket_id = ticket_data["ticket_id"]
        jira_url = self._jira_url(ticket_data)
        impact = fix_report.get("impact", {})
        fixes = fix_report.get("fixes", [])

        changes_table = self._build_changes_table(fixes)
        test_cases_section = self._build_test_cases_section(test_results)
        impact_table = self._build_impact_table(impact)

        return f"""## 🎫 Ticket: {ticket_id} – {ticket_data.get('title', '')}
**Jira**: [{ticket_id}]({jira_url}) | **Priority**: {ticket_data.get('priority', 'N/A')} | **Confidence**: {fix_report.get('confidence', 0):.0%}

---

## 🔍 Root Cause Analysis
{fix_report.get('root_cause', 'N/A')}

---

## 🛠️ Changes Made
{changes_table}

---

## ⚠️ Impact Assessment
{impact_table}

**Regression Risk**: {impact.get('regression_risk', 'N/A')}

---

## ✅ How to Test

### Run Automated Tests
```bash
robot --variable TICKET_ID:{ticket_id} \\
      --variable PLATFORM:{test_results.get('platform', 'android')} \\
      --outputdir reports/{ticket_id}/robot_output/ \\
      robot_tests/suites/generated/{ticket_id}.robot
```

### Test Results Summary
{test_cases_section}

### Test Evidence
- 📊 Robot Report: `reports/{ticket_id}/robot_output/report.html`
- 📱 Platform: {test_results.get('platform', 'android').capitalize()}
- 🔧 Run ID: `{test_results.get('run_id', 'N/A')}`
- 🕐 Executed at: {test_results.get('executed_at', 'N/A')}

---

## 📋 Checklist
- [x] Root cause identified
- [x] Fix implemented
- [x] Tests executed (Robot Framework + Appium)
- [ ] Code review done
- [ ] QA sign-off

---
*🤖 Auto-generated by AI QA Pipeline | Model: {fix_report.get('ai_model', 'N/A')} | {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}*
"""

    def _jira_url(self, ticket_data: dict[str, Any]) -> str:
        ticket_id = ticket_data["ticket_id"]
        # Construct từ env hoặc dùng placeholder
        import os
        base = os.getenv("JIRA_MCP_URL", "https://jira.company.com")
        return f"{base}/browse/{ticket_id}"

    def _build_changes_table(self, fixes: list[dict[str, Any]]) -> str:
        if not fixes:
            return "No code changes required."
        header = "| File | Change Description |\n|------|--------------------|\n"
        rows = "".join(
            f"| `{f.get('file', 'N/A')}` | {f.get('explanation', 'N/A')[:100]} |\n"
            for f in fixes
        )
        return header + rows

    def _build_impact_table(self, impact: dict[str, Any]) -> str:
        breaking = "⚠️ **YES**" if impact.get("breaking_change") else "✅ No"
        return (
            "| Area | Value |\n"
            "|------|-------|\n"
            f"| Files Changed | {impact.get('files_changed', 0)} |\n"
            f"| Risk Level | {impact.get('risk_level', 'N/A')} |\n"
            f"| Breaking Change | {breaking} |\n"
            f"| Affected Components | {', '.join(impact.get('affected_components', [])) or 'N/A'} |"
        )

    def _build_test_cases_section(self, test_results: dict[str, Any]) -> str:
        total = test_results.get("total", 0)
        passed = test_results.get("passed", 0)
        failed = test_results.get("failed", 0)
        summary = f"**{passed}/{total} PASS** | Failed: {failed}\n\n"

        cases = test_results.get("test_cases", [])
        if not cases:
            return summary

        lines = []
        for tc in cases:
            icon = "✅" if tc["status"] == "PASS" else "❌"
            lines.append(f"- {icon} `{tc['name']}`")
            if tc.get("error"):
                lines.append(f"  - Error: _{tc['error'][:120]}_")

        return summary + "\n".join(lines)

