"""
Test Generator – Sinh Robot Framework test cases từ ticket acceptance criteria
"""
import logging
import os
import re
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# Robot Framework test file template
ROBOT_TEMPLATE = """\
*** Settings ***
Documentation    Auto-generated test suite for {ticket_id}: {ticket_title}
...              Generated by AI QA Pipeline
Library          AppiumLibrary
Library          Collections
Library          String
Resource         ../../resources/common.robot
Resource         ../../resources/appium_keywords.robot
Resource         ../../resources/variables.robot
Suite Setup      Open Mobile App
Suite Teardown   Close Mobile App

*** Variables ***
${{TICKET_ID}}       {ticket_id}
${{PLATFORM}}        {platform}

*** Test Cases ***
{test_cases}

*** Keywords ***
Open Mobile App
    [Documentation]    Khởi động ứng dụng trên {platform}
    Open Application    ${{APPIUM_URL}}
    ...    platformName={platform_name}
    ...    automationName={automation_name}
    ...    deviceName=${{DEVICE_NAME}}

Close Mobile App
    [Documentation]    Đóng ứng dụng sau khi test
    Close Application
"""

TEST_CASE_TEMPLATE = """\
{tc_name}
    [Documentation]    {criteria}
    [Tags]             {ticket_id}    regression    P2    {platform}
    Log    Testing: {criteria}
    # TODO: Implement test steps based on acceptance criteria
    # Hint: {criteria}
    Pass Execution If    True    Scaffold test case – implement steps
"""


class TestGenerator:
    """Sinh .robot test suite từ ticket acceptance criteria."""

    SUITES_DIR = Path("robot_tests/suites/generated")

    def generate(self, ticket_data: dict[str, Any], platform: str = "android") -> Path:
        """
        Sinh robot test file cho ticket.

        Args:
            ticket_data: Parsed ticket data
            platform: 'android' | 'ios'

        Returns:
            Path: Đường dẫn đến file .robot được tạo
        """
        self.SUITES_DIR.mkdir(parents=True, exist_ok=True)

        ticket_id: str = ticket_data["ticket_id"]
        ticket_title: str = ticket_data.get("title", "")
        criteria_list: list[str] = ticket_data.get("acceptance_criteria", [])

        test_cases = self._build_test_cases(ticket_id, criteria_list, platform)

        content = ROBOT_TEMPLATE.format(
            ticket_id=ticket_id,
            ticket_title=ticket_title,
            platform=platform,
            platform_name="Android" if platform == "android" else "iOS",
            automation_name="UiAutomator2" if platform == "android" else "XCUITest",
            test_cases=test_cases,
        )

        suite_path = self.SUITES_DIR / f"{ticket_id}.robot"
        suite_path.write_text(content, encoding="utf-8")
        logger.debug(f"[STEP-B] Generated suite: {suite_path} ({len(criteria_list)} test cases)")
        return suite_path

    def _build_test_cases(
        self, ticket_id: str, criteria: list[str], platform: str
    ) -> str:
        cases = []
        for idx, criterion in enumerate(criteria, start=1):
            tc_name = f"TC_{idx:03d} {self._criterion_to_title(criterion)}"
            cases.append(
                TEST_CASE_TEMPLATE.format(
                    tc_name=tc_name,
                    criteria=criterion,
                    ticket_id=ticket_id,
                    platform=platform,
                )
            )
        return "\n".join(cases)

    @staticmethod
    def _criterion_to_title(criterion: str) -> str:
        """Convert acceptance criterion text thành test case title."""
        # Capitalize và giới hạn độ dài
        title = re.sub(r"[^\w\s]", "", criterion).strip()
        title = " ".join(w.capitalize() for w in title.split()[:10])
        return title or "Verify Acceptance Criteria"

